const PolicyContent = () => (
    <>
        <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

        {/* --- Interpretation and Definitions --- */}
        <h3 className="text-2xl font-bold text-slate-800 dark:text-white pt-4 pb-2">Interpretation and Definitions</h3>
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Interpretation</h4>
        <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Definitions</h4>
        <p className="mb-2">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc ml-6 mb-4 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to High Income Growth [HIG], Shathi Nagar, Palayamkottai, Tirunelveli, Tamil Nadu, India.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Tamil Nadu, India</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to HIG Ai Automation, accessible from hig-ai-automation.in</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        {/* --- Collecting and Using Your Personal Data --- */}
        <h3 className="text-2xl font-bold text-slate-800 dark:text-white pt-4 pb-2">Collecting and Using Your Personal Data</h3>
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Types of Data Collected</h4>
        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-2">Personal Data</p>
        <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, and Usage Data.</p>
        
        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-2">Usage Data</p>
        <p className="mb-4">Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, and other diagnostic data.</p>
        
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Tracking Technologies and Cookies</h4>
        <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include Cookies, Web Beacons, and other scripts.</p>
        <p className="mb-4">Cookies can be "Persistent" or "Session" Cookies. We use both types for various purposes including essential services, notice acceptance, and functionality. For more information about the cookies we use, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

        {/* --- Use of Your Personal Data --- */}
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Use of Your Personal Data</h4>
        <p className="mb-2">The Company may use Personal Data for purposes such as:</p>
        <ul className="list-disc ml-6 mb-4 space-y-2">
            <li>To provide and maintain our Service.</li>
            <li>To manage Your Account.</li>
            <li>For the performance of a contract.</li>
            <li>To contact You with updates or informative communications.</li>
            <li>To provide You with news, special offers, and general information.</li>
            <li>To manage Your requests.</li>
            <li>For business transfers like mergers or acquisitions.</li>
            <li>For other purposes, such as data analysis and improving our Service.</li>
        </ul>

        <p className="mb-2">We may share Your personal information in situations such as:</p>
        <ul className="list-disc ml-6 mb-4 space-y-2">
            <li>With Service Providers, Affiliates, and business partners.</li>
            <li>For business transfers.</li>
            <li>With other users when you interact in public areas.</li>
            <li>With Your consent for any other purpose.</li>
        </ul>

        {/* --- Retention, Transfer, and Deletion of Data --- */}
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Retention of Your Personal Data</h4>
        <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and to comply with our legal obligations.</p>

        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Transfer of Your Personal Data</h4>
        <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Delete Your Personal Data</h4>
        <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account or by contacting Us.</p>

        {/* --- Disclosure of Your Personal Data --- */}
        <h3 className="text-2xl font-bold text-slate-800 dark:text-white pt-4 pb-2">Disclosure of Your Personal Data</h3>
        <p className="mb-4">Your Personal Data may be disclosed in the case of Business Transactions, to comply with Law enforcement requests, or to meet other legal requirements such as protecting the rights and property of the Company.</p>

        {/* --- Security and Other Information --- */}
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Security of Your Personal Data</h4>
        <p className="mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        
        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Children's Privacy</h4>
        <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13 without verification of parental consent.</p>

        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Links to Other Websites</h4>
        <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h4 className="text-xl font-bold text-slate-800 dark:text-white pt-2">Changes to this Privacy Policy</h4>
        <p className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>

        {/* --- Contact Us --- */}
        <h3 className="text-2xl font-bold text-slate-800 dark:text-white pt-4 pb-2">Contact Us</h3>
        <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
        <p className="mb-4">By email: <a href="mailto:ajay@hig-ai-automation.in" className="text-indigo-600 dark:text-indigo-400 hover:underline">ajay@hig-ai-automation.in</a></p>
    </>
);

export default PolicyContent;